### PR TITLE
[new] Select an album item automatically if an artist only contains 1 AlbumItem in Zune Shell.

### PR DESCRIPTION
**Pull request by amaid**
## Overview

In Progress #129 

Following the zune desktop app, if an artist has only one albumitem in the album collection select it automatically from the album collection.

[
](https://user-images.githubusercontent.com/15306909/191950656-30f220cf-1ee8-4088-bdb5-4d7a53320a17.mp4)
## Checklist

This PR meets the following requirements:
- [x] Tested and contains **NO** breaking changes or known regressions.
- [x] Tested with the upstream branch merged in.
- [x] Tests have been added for bug fixes / features (or this option is not applicable)
- [x] All new code has been documented (or this option is not applicable)
- [x] Headers have been added to all new source files (or this option is not applicable)

## Additional info

Not provided

### CODE REVIEW

**Review by Arlodotexe — CHANGES_REQUESTED** [review]
Looks like this doesn't deselect when moving between albums. It also has issues with removing the selection state. In fact, there's a _lot_ of bugs with album selection that I hadn't noticed before.

Let's save this for after the big refactor.

**Comment by amaid** [comment]
> Looks like this doesn't deselect when moving between albums.
> 
> There's a _lot_ of bugs with album selection state when moving between artists that I hadn't noticed before. Let's save this for after the big refactor.

The deselection issue has been fixed, re the second one, zune shell CollectionContent has been refactored to use SwitchPresenter instead of relying on the visual states. This has fixed most of the major bugs.

**Review by Arlodotexe — CHANGES_REQUESTED** [review]
Found just one issue in testing - items that are added to the collection after load don't get the correct visual state applied.

https://github.com/Arlodotexe/strix-music/assets/9384894/4ba9e949-6952-4085-8bcf-bde9c6b8631e

**Comment by amaid** [comment]
> This was fixed in the latest commit.

**Comment by amaid** [comment]
> Found just one issue in testing - items that are added to the collection after load don't get the correct visual state applied.
> 
>  Recording.2023-06-12.040311.mp4

This was fixed in the latest commit.

**Review by Arlodotexe — APPROVED** [review]

**Pull request merged**
